
version: 2

models:
  - name: example__my_first_dbt_model
    description: '{{ doc("table_events") }}'
    columns:
      - name: id
        description: "The primary key for this table. This is the first table"
        tests:
          - unique
          - not_null

  - name: example__my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table. This is the second table"
        tests:
          - unique
          - not_null

  - name: example__teams_details
    description: "A list of a few NBA teams that made the Playoffs in 2020."

    columns:
      - name: team
        description: "The name of the team."

      - name: city
        description: "The home city of the team."
        tests:
          - is_la_team

      - name: state
        description: "The home state of the team."